# 机场订阅
proxy-providers:
  zsh:
    url: "https://zhs.futbol/link/whYbmVLDYRUzadUW?is_ss=5&dns=1&tj=1&disney&y2b&ai&nf"
    type: http
    interval: 86400
    proxy: DIRECT
    path: ./providers/zhs.tw.yaml

# 全局配置
mode: rule
mixed-port: 7890
redir-port: 7891
tproxy-port: 7892
allow-lan: true
bind-address: "*"
ipv6: false
unified-delay: true
tcp-concurrent: true
log-level: info
find-process-mode: 'off'
global-client-fingerprint: chrome
disable-keep-alive: false
keep-alive-idle: 600
keep-alive-interval: 15
profile:
  store-selected: true
  store-fake-ip: true
geodata-mode: false
geodata-loader: memconservative
geo-auto-update: true
geo-update-interval: 72
geox-url:
  geoip: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  metadb: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.metadb"
  asn: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/GeoLite2-ASN.mmdb"
external-controller: 0.0.0.0:9090
secret: ""
external-ui: /etc/nikki/run/ui
external-ui-name: Zashboard
external-ui-url: "https://github.com/Zephyruso/zashboard/archive/refs/heads/gh-pages.zip"

# DNS模块
dns:
  enable: true
  # cache-algorithm: arc
  listen: 0.0.0.0:1053
  ipv6: false
  respect-rules: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - "GEOSITE:private"
    - "GEOSITE:cn"
  # 用于解析DNS服务器的域名
  default-nameserver:
    - 119.29.29.29
  # 用于解析代理节点的域名
  proxy-server-nameserver:
    - 119.29.29.29
  nameserver:
    - 211.136.192.6
    - 120.196.165.24
    - 119.29.29.29

# 入站
tun:
  enable: true
  # system/gvisor/mixed
  stack: mixed
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
  dns-hijack: ["any:53", "tcp://any:53"]

# 出站策略
pr: &pr {type: select, proxies: [默认代理, 🇨🇳 台湾自动, 🇭🇰 香港自动, 🇺🇸 美国自动, 🇯🇵 日本自动, 🇸🇬 新加坡自动, 🇰🇷 韩国自动, 🇦🇺 澳洲自动, DIRECT]}
proxy-groups:
  - {name: 默认代理, type: select, proxies: [ 推荐节点, 🇨🇳 台湾自动, 🇭🇰 香港自动, 🇯🇵 日本自动, 🇸🇬 新加坡自动, 🇰🇷 韩国自动, 🇦🇺 澳洲自动, DIRECT], icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Available_1.png}
  - {name: 推荐节点, type: select, include-all: true, filter: "(?i)荐", use: [zsh], icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Auto.png}
  - {name: 漏网之鱼, <<: *pr, icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Final.png}
  - {name: 🇺🇸 美国自动, type: url-test, url: 'https://www.gstatic.com/generate_204', timeout: 5000, tolerance: 20, interval: 600, max-failed-times: 3, expected-status: 204, lazy: true,filter: "(?i)US", use: [zsh]}
  - {name: 🇨🇳 台湾自动, type: url-test, url: 'https://www.gstatic.com/generate_204', timeout: 5000, tolerance: 20, interval: 600, max-failed-times: 3, expected-status: 204, filter: "(?i)TW", use: [zsh]}
  - {name: 🇭🇰 香港自动, type: url-test, url: 'https://www.gstatic.com/generate_204', timeout: 5000, tolerance: 20, interval: 600, max-failed-times: 3, expected-status: 204, filter: "(?i)HK", use: [zsh]}
  - {name: 🇯🇵 日本自动, type: url-test, url: 'https://www.gstatic.com/generate_204', timeout: 5000, tolerance: 20, interval: 600, max-failed-times: 3, expected-status: 204, lazy: true, filter: "(?i)JP|Japan|日本", use: [zsh]}
  - {name: 🇸🇬 新加坡自动, type: url-test, url: 'https://www.gstatic.com/generate_204', timeout: 5000, tolerance: 20, interval: 600, max-failed-times: 3, expected-status: 204, lazy: true, filter: "(?i)SG|Singapore|新加坡", use: [zsh]}
  - {name: 🇰🇷 韩国自动, type: url-test, url: 'https://www.gstatic.com/generate_204', timeout: 5000, tolerance: 20, interval: 600, max-failed-times: 3, expected-status: 204, lazy: true, filter: "(?i)KR|Korea|韩国", use: [zsh]}
  - {name: 🇦🇺 澳洲自动, type: url-test, url: 'https://www.gstatic.com/generate_204', timeout: 5000, tolerance: 20, interval: 600, max-failed-times: 3, expected-status: 204, lazy: true, filter: "(?i)AU|Australia|澳洲|澳大利亚", use: [zsh]}
  - {name: YouTube, <<: *pr, icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/YouTube.png}
  - {name: ChatGPT, <<: *pr, icon: https://fastly.jsdelivr.net/gh/shindgewongxj/WHATSINStash@master/icon/openai.png}
  - {name: Telegram, <<: *pr, icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Telegram.png}
  - {name: TikTok, <<: *pr, icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/TikTok.png}
  - {name: GitHub, <<: *pr, icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/GitHub.png}
  - {name: Google, <<: *pr, icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Google_Search.png}
  - {name: Apple, type: select, proxies: [DIRECT,  默认代理], icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Apple.png}
  - {name: 全部节点, type: select, use: [zsh], icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Global.png}

# 规则匹配
rules:
  - DOMAIN-SUFFIX,cn.bing.com, 默认代理
  - DOMAIN-SUFFIX,th.bing.com, 默认代理
  - GEOSITE,private, DIRECT
  - GEOSITE,category-scholar-!cn, 默认代理
  - GEOSITE,steam@cn, DIRECT
  - GEOSITE,category-games@cn, DIRECT
  - GEOSITE,apple-cn, Apple
  - GEOSITE,apple, Apple
  - GEOSITE,category-ai-!cn, ChatGPT
  - GEOSITE,github, GitHub
  - GEOSITE,youtube, YouTube
  - GEOSITE,google, Google
  - GEOSITE,telegram, Telegram
  - GEOSITE,microsoft@cn, DIRECT
  - GEOSITE,onedrive, DIRECT
  - GEOSITE,tiktok, TikTok
  - GEOSITE,gfw, 默认代理
  - GEOSITE,geolocation-!cn, 默认代理
  - GEOSITE,cn, DIRECT
  - GEOIP,private, DIRECT,no-resolve
  - GEOIP,google, Google,no-resolve
  - GEOIP,telegram, Telegram,no-resolve
  - GEOIP,cn, DIRECT
  - MATCH, 漏网之鱼
