// Package vmc is the G1 migration of the vmc output parsing and version
// selection that md_tool/md.sh currently implements with awk/sed/grep
// one-liners. This package contains only pure parsing and selection: it does
// not run `vmc`, open SSH connections or render TUI. A later stage (G5 per
// md_go/GO_REFACTOR_PLAN.md, "vmc/install/upgrade/rollback 迁移") will drive
// these functions with the runner and config packages.
//
// # md.sh ↔ vmc package mapping
//
// | md.sh function                    | vmc package call                                    |
// |-----------------------------------|-----------------------------------------------------|
// | vmc::_get_current_ver             | ParseList + FindCurrentVersion                      |
// | vmc::_get_latest_ver              | ParseSearch + LatestVersion                         |
// | vmc::finstall (name-pick awk)     | ParseSearch + SelectPackageByVersion                |
// | vmc::rollback (verbose awk rows)  | ParseSearchVerbose + MatchPackage                   |
// | vmc::rollback render+sort+filter  | not modelled — see "rollback rendering & filter"    |
// | vmc::install _extract + packages  | ParseEditText + DefaultVersionSpecs + ExtractEditVersion |
// | vmc::upgrade / check_updates diff | compare FindCurrentVersion vs LatestVersion results  |
//
// # Input formats
//
// ## vmc list (ParseList)
//
// Installed-package listing. md.sh relies on each row being
// "<name> <version>..." ($1 = name, $2 = version); the version column may be
// parenthesized — md.sh strips '()' with `tr -d`, so `mdrive (1.2.3)` and
// `mdrive 1.2.3` both yield Version "1.2.3".
//
//	Source: md.sh vmc::_get_current_ver / the `vmc list | awk '{print "#   "
//	$1 ": " $2}'` template in vmc::install.
//
// ## vmc fsearch, plain (ParseSearch)
//
// One record per line, rendered by vmc itself as
// `name: %v, version: %v, platform: %v` (the exact literal found in the vmc
// release binary vmc_linux_amd64_0.0.151 shipped under
// /home/mini/dev/myScript/vmc_deploy/ — a sibling of md_tool, outside this
// git repo):
//
//	name: mdrive, version: test.4.0.1.mdrive4_zc_full_test_0811, platform: orin
//
//	Sources: the vmc binary literal above, plus the awk in vmc::finstall that
//	splits every `/^name:/` line on ", " and reads the `name:` / `version:`
//	fields, and the `_get_latest_ver` sed capture of the version field.
//
// ## vmc fsearch --verbose (ParseSearchVerbose)
//
// Record blocks. vmc prints one `[Index:%v|ID:%v]` line per hit followed by
// Name / Version / Platform / ReleaseTime field lines; md.sh's rollback awk
// reconstructs one row per block and emits `time | version | platform | name`.
// The name can appear inline on the Index line
// (`[Index:3|ID:abc] name: mdrive,`) or on a dedicated field line — the awk
// handles both and the parser reproduces that.
//
//	Sources: the `[Index:%v|ID:%v]` / `ReleaseTime: %v` literals in the vmc
//	release binary, and the field-state-machine awk in vmc::rollback.
//
// Fixture examples for every shape above (plus CRLF, quote, colon and
// comma-noise variants) live in parser_test.go, each annotated with its
// format source.
//
// ## `md install` pasted text (ParseEditText)
//
// The text pasted into the vi editor (usually copied from a release
// notification or generated by the `vmc list` template) is scanned per spec.
// Each spec mirrors one entry of the md.sh `packages` array:
//
//	mdrive       keywords [mdrive]
//	mdrive_conf  keywords [mdrive_conf, conf]
//	mdrive_map   keywords [mdrive_map, map]
//	mdrive_dep   keywords [mdrive_dep, dep]
//	mdrive_model keywords [mdrive_model, model]
//
// A line is a match when it starts (after optional spaces) with one keyword
// followed by a non-identifier boundary. `mdrive:` never matches the line
// `mdrive_conf: ...` because '_' is an identifier char — the same guard as
// the awk regex `^[[:space:]]*(pattern)([^_a-zA-Z0-9]|$)`.
//
//	Source: vmc::install `_extract` grep + sed chain in md.sh.
//
// # vmc::rollback rendering and platform filter (not modelled)
//
// Beyond the verbose awk that ParseSearchVerbose + MatchPackage mirror, the
// rollback pipeline adds two steps that this package deliberately does NOT
// model (YAGNI — recorded for G5, no function added):
//
//  1. each awk record is rendered as `time | version | platform | name` and
//     sorted descending with `sort -r`;
//  2. the display list is filtered for fzf with
//     `grep -E "$VMC_PLATFORM|any"`.
//
// That filter is case-sensitive and greps the whole rendered row. It must NOT
// be modelled on LatestVersion/platformMatch, which mirrors _get_latest_ver's
// `grep -iE "${platform:-orin}|any"`: case-insensitive, whole raw
// `name: ..., version: ..., platform: ...` line, with a `${platform:-orin}`
// default — a different variable, different casing and a different input.
// VMC_PLATFORM is never defined in md.sh; it is exported by the sibling
// vmc_deploy/vmc.sh:16 as "amd64", so G5 has to decide where it comes from
// and what the default is.
//
// # Deliberate divergences from the Bash awk behaviour
//
// The parsers stay faithful to what the awk one-liners DO (record grouping,
// flush rules, name precedence, first-match semantics), but normalize noise
// that the awk would leak into downstream values:
//
//   - CRLF is stripped before parsing anywhere (Bash only tolerated \r in the
//     final `tr -d` steps of each pipeline).
//   - Field names are matched case-insensitively (Bash only tolerated case
//     for the Name label, and only letter n).
//   - `label:value` and `label : value` (space between label and colon) both
//     parse (Bash awk needed whitespace after the label to see a value, and
//     needed the colon glued to the label).
//   - Stray quotes, trailing commas and trailing '}' are trimmed from values
//     (the awk kept them in fields it extracted via `$1=""` or the inline
//     name cut).
//   - The edit-text extractor operates on runes, so a full-width separator
//     (：/（/）) next to the keyword is consumed cleanly; under md.sh's
//     LC_ALL=C the equivalent sed would mangle multi-byte characters.
//   - FindCurrentVersion keeps the FIRST row for a duplicated package name;
//     the awk `grep "^<pkg> "` matches every row and the Bash `tr -d` would
//     have concatenated the versions (see the comment on FindCurrentVersion).
//   - The whitespace normalisation asymmetry between LatestVersion (drops
//     whitespace only, like `_get_latest_ver`'s `tr -d '[:space:]'`) and
//     FindCurrentVersion (also drops parentheses, like `_get_current_ver`'s
//     `tr -d '[:space:]()'`) is a faithful replica of md.sh — G5 must not
//     normalise only one side when computing the upgrade diff.
//   - splitLines treats a lone \r (not preceded by \n) as a line break, while
//     the Bash _extract chain only removed \r in place (`s/\r//g`). The
//     divergence only affects bare-\r text with no \n at all, which is rare.
//
// # Connection to later stages
//
// G5 will compose these primitives into the vmc flow: run `vmc fsearch` /
// `vmc list` through internal/runner, ParseSearch/ParseList the output,
// resolve targets with SelectPackageByVersion / LatestVersion / MatchPackage,
// and drive `md install` edits with ParseEditText. The `any` fallback and the
// case-insensitive platform keyword of _get_latest_ver are modelled by
// LatestVersion; the rollback display filter (VMC_PLATFORM) is deliberately
// NOT modelled — see "vmc::rollback rendering and platform filter" above.
// Nothing in this package should ever change when the vmc CLI or the
// config/env handling evolves — only the parser fixtures would need updating
// if a real `vmc` output shape turns out to differ from the reconstructed
// fixtures.
package vmc
